# Generated by Django 5.1.2 on 2024-10-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_alter_transaction_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
