# Generated by Django 5.1.2 on 2024-11-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0006_transaction_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='end_date',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='account',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
    ]
