# Generated by Django 5.1.2 on 2024-11-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0008_remove_budget_amount_budgetcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
    ]
