# Generated by Django 5.1.2 on 2024-11-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0009_remove_budget_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
