# Generated by Django 5.1.2 on 2024-11-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0006_task'),
        ('finance_app', '0010_alter_budgetcategory_category'),
    ]

    operations = [
    ]
